version: '3.7'
services:
  web:
   build: web/
   container_name: web
   command: sh -c "sleep 10s; python3 ./manage.py runserver 0.0.0.0:8000"
   depends_on:
     - mydb
   ports:
     - '8000:8000'
     - '5000:5000'
   expose:
     - '8000'
     - '5000'
  mydb:
    build: db/
    restart: always
    container_name: mydb
    environment:
      MYSQL_DATABASE: 'devblog'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
